### ISSUE TITLE
index.js src

### ISSUE THREAD

**Issue by idkjs** [sgrove/powertiller#1]
Error:
```
Loading failed for the <script> with source “http://localhost:5000/src/index.js”.
```

Fixed in `index.html` with:

```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>PowerTiller for Eventil</title>
</head>

<body>
  <div id="index"></div>
  <script src="../build/index.js"></script>
</body>

</html>
```

Result gets ui but throw auth error:

![screenshot_2018-09-03 powertiller for eventil](https://user-images.githubusercontent.com/2370391/44996525-a6a50800-afa8-11e8-80c5-89e2c50c17a4.png)

**Comment by sgrove** [comment]
Thanks for this bug report! There are two things here - first you need to authenticate with the github/youtube buttons on the upper right (might have to go through a few times), and second Eventil had moved around their schema in some breaking ways.

This was a great bug report for us to start building some tooling that'll make it immediately apparent for upstream API providers to know when they're making breaking changes. Thank you!

**Comment by sgrove** [comment]
Also, here's an example of what it looks like when it's running correctly

![screenshot 2018-09-10 17 02 07](https://user-images.githubusercontent.com/35296/45330658-533c3800-b51b-11e8-9982-039b15f3f258.png)
